spring:
#  data:
#    web:
#      pageable:
#        default-page-size: 2
#        max-page-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/City
    username: "postgres"
    password: "root"
  liquibase:
    change-log: changeLog/db.changelog.yml
    enabled: true
    password: root
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    ddl: update
